language: python

branches:
  only:
  - master

python:
  - '3.7'

install:
  - pip install -r requirements.txt
  - pip install -U pytest pytest-cov codecov

script:
  - pytest tests/ --cov=./multiview/

after_success:
  - codecov
